### ISSUE TITLE
assignment count mismatch: 2 = 3

### ISSUE THREAD

**Issue by wiless** [golang/lint#105]
Was trying out `go get` based on the instructions. Got this error on the shell

```
 go get github.com/golang/lint/golint 
# github.com/golang/lint
goapps/src/github.com/golang/lint/lint.go:1432: assignment count mismatch: 2 = 3
```

Running Kubuntu, 14.10 and go1.4 (64bit)
Thanks

**Comment by zimmski** [comment]
Solution: `go get -u golang.org/x/tools`
Duplicates 103 99 97 93 92
@dsymonds: Since @wiless tried the README instructions this PR  #104 would help.

**Comment by wiless** [comment]
@dsymonds Thanks, it works.
