### ISSUE TITLE
Flag Tcp?

### ISSUE THREAD

**Issue by cespare** [golang/lint#110]
Is it OK to flag Tcp (should be TCP)? Happy to send a pull request over.

**Comment by dsymonds** [comment]
Golint does not have an exhaustive list of initialisms to flag. It's not going to get them all, nor is it always going to be right. I don't think we need to chase down every single one; use human judgment instead.

**Comment by cespare** [comment]
Yeah I understand the desire to not maintain an ever-expanding list. It does seem like TCP/UDP are common initialisms that are missing from among similar networking-related terms: DNS, IP, HTTP, URI. Also TCP/UDP both fit the criterion of not being likely to be false positives.

**Comment by dsymonds** [comment]
That's fair enough. It's easier for me to do small ones, so I'll take care
of it.

**Comment by cespare** [comment]
Thanks!
