### ISSUE TITLE
lack of detection of local variable and global variable using same name

### ISSUE THREAD

**Issue by dunty** [golang/lint#117]
for example:

```
var c redis.Conn
func main() {
	c, err := redis.Dial("tcp", "redis:6379")
	defer c.Close()
	http.HandleFunc("/", Returnresult)
	http.ListenAndServe(":"+port, nil)
}

func Returnresult(rw http.ResponseWriter, r *http.Request) {
	n, err := redis.Int(c.Do("INCR", "counter"))
....
}
```

this code will produce a panic because c in Returnresult is a nil pointer.

**Comment by dsymonds** [comment]
It happens, but you learn to avoid it, and typically discover it easily enough. Golint isn't the right tool to detect that anyway. Govet has a `-shadow` flag that is awfully noisy but I believe would spot something like this.
