### ISSUE TITLE
ID vs Id

### ISSUE THREAD

**Issue by ydnar** [golang/lint#124]
On https://github.com/golang/lint/blob/master/lint.go#L706, golint warns for fields named `...Id` and suggests renaming to `...ID`:

`example/client.go:12:2: struct field ClientId should be ClientID`

In code, `id` is typically used an abbreviation for “identifier,” rather than an acronym. The Go standard library is inconsistent here, using both `ID` and `Id`. Should golint tolerate this, or suggest the inverse?

**Comment by dsymonds** [comment]
The standard library is unable to be changed now, but its uses of `Id` are largely in error. `ID` is the correct style, just like `HTTP` and `URL` are.

**Comment by ydnar** [comment]
@dsymonds HTTP is an acronym. “id” is an abbreviation.

**Comment by dsymonds** [comment]
The check is for initialisms, not acronyms; in this sense, the style is to follow how you'd write it in prose, which is `ID` or `HTTP`.

**Comment by thiagocaiubi** [comment]
For the reference on initialisms: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Comment by spellgen** [comment]
ID is an initialism if you think of it as Identity Document. If you thought it meant Identifier that doesn't work so well.

**Comment by lenqnr** [comment]
What about the plural form `Ids`? Should it be warned to rename to `IDs` as well for consistency?

**Comment by dyslexicanaboko** [comment]
Honestly this feels like being different for the sake of being different. What is wrong with your standard camelCase and PascalCase? Making an exception just for "ID" makes no sense and just feels like bias to me. Follow one pattern and remove exceptions. Every time there is an exception this is how confusion occurs.
