### ISSUE TITLE
Report needless []byte -> string conversion for Printf arguments

### ISSUE THREAD

**Issue by extemporalgenome** [golang/lint#127]
I frequently encounter code like the following in the wild:

    var buf []byte
    // ...
    fmt.Printf("%s\n", string(buf))

Since the %s and %q format specifiers treat []byte and string identically, there's no reason for the pointless conversion to string.

**Comment by dsymonds** [comment]
Maybe, though something like this might be more in line with govet's scope, which does a bunch of other format string checking.

**Comment by extemporalgenome** [comment]
Yeah, I was wondering about that too. Strictly speaking, it's not a matter of correctness, since the output/behavior does not change in either case, yet it's completely redundant, thus not quite in the realm of style.

**Comment by dsymonds** [comment]
I think I'll err on the conservative side and say "no". Thanks anyway.

**Comment by zimmski** [comment]
This checks for redundancy. For me this is like the check for "should omit 2nd value from range; this loop is equivalent to `for i := range ...`" which is part of golint.

@extemporalgenome if you want to implement this in vet have a look at https://github.com/golang/tools/blob/master/cmd/vet/print.go and post your plan in the golang-dev mailing list.
