### ISSUE TITLE
Returning multiple errors from a func confuses golint

### ISSUE THREAD

**Issue by ahmetalpbalkan** [golang/lint#133]
I have a function like this:

    func createError(xmlBody []byte) (serviceError error, err error)

It creates an error called `serviceError` from the given HTTP response body. And something goes wrong during that (the XML deserialization & so forth), it returns an error called `err`.

golint says:

    error should be the last type when returning multiple items

well, it actually is?

**Comment by dsymonds** [comment]
It's a weird Go API that returns two errors. Much more normal is to return a single error and let the caller distinguish different classes of errors if needed. You appear to be returning an `error` for something that isn't actually an error; it might be clearer to return the concrete type instead.

**Comment by ahmetalpbalkan** [comment]
I agree it's weird but if you're making a type declaration

    type errFunc func(body []byte) (error, error)

and two implementations would return `(ErrA, error)`, `(ErrB, error)` then they don't conform to errFunc

**Comment by dsymonds** [comment]
Well, golint is about nudging people to write Go in the commonly accepted style, and that's not a standard Go API, so I'd say that golint is working as intended. Perhaps you might want to rethink how your code is working, or else just ignore what golint is saying for it.

**Comment by ahmetalpbalkan** [comment]
Thanks @dsymonds. I'll probably merge two errs into one.
