### ISSUE TITLE
disable exported method checks for main package

### ISSUE THREAD

**Issue by napsy** [golang/lint#137]
Is it necessary to check for undocumented methods that are exported, but reside inside the ``main`` package where the methods will be used inside that package anyhow?

I propose a flag that would ignore the warning if the exported method is inside the main package

**Comment by dsymonds** [comment]
We're not going to be adding flags to control which warnings are printed.

If an exported method is on an exported type in package main, that means other packages can import it, and it should be documented. That'll also make it easier to move that type to its own package later on too. If it doesn't warrant even a simple doc comment then either unexport the method or unexport the type.
