### ISSUE TITLE
underscores in cgo exported functions

### ISSUE THREAD

**Issue by GeertJohan** [golang/lint#144]
In c-style API's it is common to use underscores.

So when implementing a C API:

``` go
//export some_api_function
func some_api_function(argument string) (retval C.int) {
    // implementation...
}
```

golint throws the error: `don't use underscores in Go names; func some_api_function should be someAPIFunction`.

Can this error message be suppressed? I think it is hardly ever useful. In fact, I think most golint errors should be suppressed on exported functions. If only this one is suppressed, then it will probably give the "api should be API" message which also doesn't apply here..

**Comment by dsymonds** [comment]
You're not implementing a C API there. You're implementing a Go API, wrapping a C API. Your callers will want to feel like they are calling a Go function, not a C function.

**Comment by dsymonds** [comment]
See #138 (the pull request that caused cgo files to be checked) for a related discussion.

**Comment by GeertJohan** [comment]
@dsymonds I'm not sure we're are talking about the same thing. This code is compiled into a shared object and loaded by a C program, using Go1.5's `-buildmode=c-shared`. The C program calls `some_api_function`. The function is never called from Go code.

What I mean with "implementing a C API" is that the API outline is already defined in the C program, and my Go .so must conform to it to be compatible.

I think golint should ignore function names when they are exported as defined in the [cgo documentation](http://golang.org/cmd/cgo/#hdr-C_references_to_Go) (`//export`).

**Comment by dsymonds** [comment]
Maybe you and @dominikh should come to some agreement on this. He said the opposite on #138.

**Comment by GeertJohan** [comment]
I already agree with @dominikh: he is talking about C code being wrapped in Go. When wrapping a C library in a Go package, the API should definitely conform to Go styling standards. Take for example this wrap taken from the libusb that's linked in #138:
```c
ssize_t LIBUSB_CALL libusb_get_device_list(libusb_context *ctx, libusb_device ***list);
```
becomes
```go
func (ctx *Context) GetDeviceList() ([]*Device, error)
```

golint should indeed print errors if it was wrapped to `Get_Device_List`.

But that has nothing to do with cgo-exported functions that I opened this issue for. In my case, a C program is able to load plugins (written in Go) as shared object. It expects the plugin to provide a certain set of exported symbols (functions). The names of those functions are predefined and therefore must match the expectations of the program that loads the shared object. If I export the functions as `SomeAPIFunction` instead of `some_api_function`, it simply won't work.

I think cgo files should still be linted. Only the exported functions should be ignored. They are being used from C, not from Go.

**Comment by dsymonds** [comment]
Ah, by "exported" you mean in the linker sense rather than the Go sense.

Yeah, seems like we should avoid linting any signature tagged with `//export`.

**Comment by bcmills** [comment]
I'm planning to give this a try soon.
