### ISSUE TITLE
go get doesn't work.

### ISSUE THREAD

**Issue by OscarRyz** [golang/lint#149]
It looks like a dependency of golint changed because I can't perform go get
```
$ go get  github.com/golang/lint/golint
# github.com/golang/lint
src/github.com/golang/lint/lint.go:1480: too many arguments in call to types.Eval
```

**Comment by OscarRyz** [comment]
BTW if I perform go get types before it works without problems.

    go get golang.org/x/tools/go/types
    go get  github.com/golang/lint/golint

**Comment by dsymonds** [comment]
That's why the README says to pass `-u` to `go get`. You need to use the latest version of x/tools.

**Comment by rfink** [comment]
I did the "go get" on types and still get the same error message:

../../../github.com/golang/lint/lint.go:1480: too many arguments in call to types.Eval
../../../github.com/golang/lint/lint.go:1480: assignment count mismatch: 2 = 3

**Comment by dsymonds** [comment]
Run `go get -u golang.org/x/tools/go/types` and try again.

**Comment by rfink** [comment]
Same thing

go get -u golang.org/x/tools/go/types
Ryans-MacBook-Pro-2:glew-cortex (master*) $ go get -u github.com/golang/lint/golint
# github.com/golang/lint
../../../github.com/golang/lint/lint.go:1480: too many arguments in call to types.Eval
../../../github.com/golang/lint/lint.go:1480: assignment count mismatch: 2 = 3

**Comment by dsymonds** [comment]
I don't know what else to suggest except clearing out your GOPATH and starting over. The signature to types.Eval changed ages ago; you've got an out of date version of something. Maybe your x/tools repo is pointing at the old code.google.com location.

**Comment by rfink** [comment]
Thanks, that worked.  Not really sure how that happened.

**Comment by shirayu** [comment]
I faced the same problem.
I solved this by ``go get -u golang.org/x/tools/go/types`` after remove ``$GOPATH/src/golang.org/x/tools``.

The old repository seemed to use Mercurial, while the current one uses git.
This caused the failing of ``go get -u golang.org/x/tools/go/types``.
