### ISSUE TITLE
too many arguments in call to types.Eval on build and testing

### ISSUE THREAD

**Issue by d4rk5eed** [golang/lint#150]
➜  lint git:(master) go test     
\# github.com/golang/lint
./lint.go:1480: too many arguments in call to types.Eval
./lint_test.go:281: too many arguments in call to types.Eval
FAIL    github.com/golang/lint [build failed]

➜  lint git:(master) go version 
go version go1.4.2 linux/amd64

**Comment by dsymonds** [comment]
You have a stale `x/tools` repo. Run the command in the README.
