### ISSUE TITLE
add support for GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by toxeus** [golang/lint#151]
For background see [here](https://groups.google.com/d/msg/golang-dev/74zjMON9glU/4lWCRDCRZg0J) and [here](https://groups.google.com/d/msg/golang-dev/74zjMON9glU/EOKSoaL5p8wJ). Therefore, `golint` will blindly check vendored dependencies when `GO15VENDOREXPERIMENT=1`. Since we cannot expect all dependencies to be `golint` compliant the `vendor` folder should be ignored by `golint` when `GO15VENDOREXPERIMENT=1`.

**Comment by dsymonds** [comment]
I'm not sure ignoring is right. The `go` tool doesn't ignore vendored packages if you use it with a `./...` argument; why should `golint`?

**Comment by toxeus** [comment]
> why should `golint`?

I think that it's pretty sane to assume that your dependencies should not fail on `go build` and `go test` and therefore not ignore the dependencies when specifying `./...` for the `go` tool. 

For `golint` it's a different story because - as of now - most go packages are not `golint` compliant. IMHO it would be the wrong thing to punish a project that tries to be `golint` compliant by making it work around the dependencies' `golint` errors.

Alternatively, a `-ignore` flag could be provided. But is certainly much less convenient.

**Comment by brocaar** [comment]
@adg proposed to use this workaround for the ``go`` tool (https://github.com/golang/go/issues/11659):
 ```
go install $(go list ./... | grep -v /vendor/)
```

Maybe we could make this work for the ``golint`` tool too (``golint $(go list ./... |grep -v /vendor/)``)?
It seems that now the ``golint`` tool parses the arguments provided by ``go list ./...`` as files and thus resulting in the error ``no such file or directory`` for each package.

**Comment by ascarter** [comment]
In my opinion, the go tool should be ignoring vendor - to me this code should be exactly like library code in your workspace, just in the vendor/. I think vendor is a snapshot that most people would want to leave untouched. If you did want to locally fork in vendor, explicitly providing <gotool> vendor/path/to/thing seems perfectly fine. I'm betting the 90% case is like what @toxeus, @brocaar, and I are experiencing.

Adding ignore option would be an ok workaround. @brocaar - thanks for the workaround - that unblocks our CI for the time being.

**Comment by ifraixedes** [comment]
I agree with @ascarter
Many thanks @brocaar for the workaround

**Comment by dsymonds** [comment]
golang/go#12278 is probably going to be the right solution. Every tool that operates on Go packages shouldn't hack in their own mechanism for handling vendored packages.

**Comment by fiorix** [comment]
@brocaar you can do that with a one-liner: `go list ./... | grep -v /vendor/ | xargs -L1 cmd` where `cmd` is golint or whatever.

**Comment by paddyforan** [comment]
Just wanted to chime in that this is currently kind of non-obvious, and a workaround being documented better (or supporting the same workaround used for the `go` command) would be a great step forward, in my opinion. I have some thoughts about how to add support in a non-breaking-change way, but none are particularly elegant (add it as a flag option, allow multiple package paths to be passed, etc.) I'd be happy to take a crack at it, if it's a desirable change.

**Comment by dsymonds** [comment]
`GO15VENDOREXPERIMENT` support is not going to happen because that env var is going away. It was a transitional hack.

`golint` isn't going to intentionally skip `vendor` dirs for the same reason that the `go` tool doesn't. There' easy workarounds as are listed above.

The only remaining piece is to make sure that vendored imports are actually type checked correctly, and that only requires switching golint to using the `go/types` package in the standard library. I'll be doing that shortly.

**Comment by nathany** [comment]
It would be very nice if `golint $(go list ./... | grep -v vendor)` worked for consistency between go tools -- such as when creating a makefile. As mentioned in https://github.com/golang/lint/issues/151#issuecomment-129730670, golint doesn't like a list of packages.

```
open github.com/org/repo: no such file or directory
open github.com/org/repo/pkg: no such file or directory
```

**Comment by toxeus** [comment]
@dsymonds wrote:
> `golint` isn't going to intentionally skip `vendor` dirs for the same reason that the `go` tool doesn't. There' easy workarounds as are listed above.

With the release of Go 1.9 the `go` tool is intentionally skipping `vendor` dirs. See the [release notes](https://golang.org/doc/go1.9#vendor-dotdotdot) and the [discussion on github](https://github.com/golang/go/issues/19090). I suggest that for the same reason `golint` should also intentionally skip `vendor` dirs.

**Comment by nathany** [comment]
see #320 as this issue is closed

**Comment by toxeus** [comment]
@nathany Github issues are like doors - it's possible to re-open them when they're closed 😉 

The reason why I've commented in this issue is because @dsymonds has explained in this issue that one goal for `golint` is aligning its CLI with `go` tool's CLI.
