### ISSUE TITLE
List of lint verification items

### ISSUE THREAD

**Issue by Integralist** [golang/lint#156]
> "Govet is concerned with correctness, whereas golint is concerned with coding style"

Is there a concrete list of items that `go lint` tries to verify against? 

This page https://github.com/golang/go/wiki/CodeReviewComments is provided as a reference, but it's not clear if `go lint` actually validates against all these things, or just some of them?

The distinction between `go lint` and `go vet` also isn't clear, they seem very similar.

Any help or guidance is appreciated.

Thanks

**Comment by dsymonds** [comment]
There isn't a list, except in the source code. It's not meant to be verifying a checklist, only making suggestions about a bunch of things.

I'm not sure how I can make the lint/vet distinction any clearer. Coding style is independent of code correctness; one affects how your program reads, and one determines if your program runs correctly.
