### ISSUE TITLE
Update Travis configuration to test a variety of Go versions

### ISSUE THREAD

**Issue by vielmetti** [golang/lint#159]
Travis can test multiple versions of Go. A simple patch provided in the attached PR does that.

As of this writing, all tests pass on 1.4, 1.5, 1.5.1 and "tip".

**Comment by dsymonds** [comment]
I'm not sure there's much gain here. The typical way that golint breaks with older versions is when a dependency breaks (e.g. `golang.org/x/tools/go/types`), which isn't going to be identified accurately by this.
