### ISSUE TITLE
Exit status code is always 0

### ISSUE THREAD

**Issue by serejja** [golang/lint#163]
Hi,

I'd like to integrate golint check to my CI build so that it consists from `go vet`, `golint` and `go test -v` calls. The problem here is that even when golint outputs warning messages the exit code is still 0 thus making tests green when they shouldn't.

Is there any chance to get this behave like go vet and go test?
Thanks

**Comment by dsymonds** [comment]
Don't use golint in a CI. It doesn't belong there. Read the README and the previous issues.
