### ISSUE TITLE
I got  errors when install lint

### ISSUE THREAD

**Issue by xiangjihan** [golang/lint#169]
Commands and errors(I wanna install lint  to global environment):
[root@localhost ~]# go get github.com/golang/lint
/usr/share/gocode/src/github.com/golang/lint/lint.go:1496:16: 错误：reference to undefined field or method ‘Type’
  if b, ok := tv.Type.(*types.Basic); ok {
                ^
/usr/share/gocode/src/github.com/golang/lint/lint.go:1492:19: 错误：function result count mismatch
  tv, err := types.Eval(f.fset, f.pkg.typesPkg, expr.Pos(), exprStr)
OS:Fedora 23 VMwrea 12 pro
Go version :go1.4.2 gccgo (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4) linux/amd64 
My golang envs:
GOARCH="amd64"
GOBIN="/usr/lib/golang/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/gocode"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/libexec/gcc/x86_64-redhat-linux/5.1.1"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/usr/bin/g++"
CGO_ENABLED="1"
What can I do to solve this issue?

**Comment by dsymonds** [comment]
You have out of date dependencies. Run `go get -u github.com/golang/lint` instead.
