### ISSUE TITLE
install error?!

### ISSUE THREAD

**Issue by eau-u4f** [golang/lint#173]
```
$ go get  github.com/golang/lint/golint
# github.com/golang/lint
../../../github.com/golang/lint/lint.go:1492: too many arguments in call to types.Eval
../../../github.com/golang/lint/lint.go:1492: assignment count mismatch: 2 = 3
```
while trying to install... do I miss something obvious ?

**Comment by zimmski** [comment]
Run `go get -u github.com/golang/lint`

**Comment by eau-u4f** [comment]
```
$ go get -u  github.com/golang/lint/golint
# github.com/golang/lint
../../../github.com/golang/lint/lint.go:1492: too many arguments in call to types.Eval
../../../github.com/golang/lint/lint.go:1492: assignment count mismatch: 2 = 3

```
same

**Comment by eau-u4f** [comment]
```
$ go get -u  github.com/golang/lint       
# github.com/golang/lint
../../../github.com/golang/lint/lint.go:1492: too many arguments in call to types.Eval
../../../github.com/golang/lint/lint.go:1492: assignment count mismatch: 2 = 3

```

**Comment by zimmski** [comment]
Hm. Try `go get -u golang.org/x/tools/go/type` please.

**Comment by dsymonds** [comment]
You probably have a really old `golang.org/x/tools/go/types` (before it moved). If @zimmski's suggestion above doesn't work, delete `$GOPATH/src/golang.org/x/tools/go/types` and start again.

**Comment by eau-u4f** [comment]
yes indeed, i removed the entire golang.org to force checking out everything properly.. and indeed it works fine.
too bad go don't handle that when -u...
thanks

**Comment by zimmski** [comment]
@dsymonds: I already forgot that "-u" does not fetch updates for existing projects. Do you think that this might be a valid addition to `go get`?

**Comment by dsymonds** [comment]
Maybe. I think we had previously discussed at least `go get` knowing about the old `code.google.com` subrepos and warning folk. That would be worth considering. File a bug at https://golang.org/issue/new ?

**Comment by zimmski** [comment]
I opened golang/go#13332
