### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by martinrusev** [golang/lint#183]
I am getting the following error on Windows 10:

```
go get  github.com/golang/lint/golint
# github.com/golang/lint
...\go\src\github.com\golang\lint\lint.go:1492: too many arguments in call to types.Eval
```

**Comment by dsymonds** [comment]
It's got nothing to do with Windows. You have an out of date `golang.org/x/tools` repo. Delete `$GOPATH/src/golang.org/x/tools` and run that `go get` command again.

**Comment by martinrusev** [comment]
Thanks. Works fine now
