### ISSUE TITLE
go get -u github.com/golang/lint/golint

### ISSUE THREAD

**Issue by jianfengye** [golang/lint#184]
show error:

package golang.org/x/tools/go/gcimporter: unrecognized import path "golang.org/x/tools/go/gcimporter"
package golang.org/x/tools/go/types: unrecognized import path "golang.org/x/tools/go/types"

how to deal with that?

**Comment by dsymonds** [comment]
Try deleting `$GOPATH/src/golang.org/x/tools` and run it again. You probably have an out of date or broken x/tools repo.
