### ISSUE TITLE
Problematic outdent recommendation

### ISSUE THREAD

**Issue by DanCripe** [golang/lint#185]
When code is structured like this:

if condition {
        return expression2
} else {
        return expression2
}

...golint recommends that the else be deleted and the "return expression2" be outdented. However, when the code is of the form:

if var := expression1; condition {
        return expression2
} else {
        return expression3
}

...it may be the case that var is needed to execute the conditional code in both the if and else sections. In this case, the deletion of the else and outdenting the second return makes var out-of-scope.

golint should not recommend the outdent unless it has verified that the outdented code is not dependent on the result of the conditional expression calculation.

**Comment by dsymonds** [comment]
https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow explains what to do in that situation: move the var assignment outside the if. Golint mentions that.

**Comment by DanCripe** [comment]
I disagree. I can use the pattern:

if var = expression; condition {
    code
} else {
   code
}

...anywhere - except when there's a closing return in the first block of code. Making me change a coding style (which is idiomatic to golang) because the code *could* be written in a way that skips the else (by promoting the locally-scoped variable to a higher scope) is unreasonable.

**Comment by dsymonds** [comment]
The doc I linked to is documenting the idiomatic coding style. That you disagree with that style is understood, but it's what golint is working against. The decision is that keeping indentation minimal outweighs the scope limitation when those two conflict.

No-one is making you do what golint says. If you think you know better, ignore it.
