### ISSUE TITLE
go lint finds errors in generated stringer files

### ISSUE THREAD

**Issue by purpleidea** [golang/lint#187]
Unfortunately, the stringer module likes to add underscores which golint finds. Perhaps it could detect and ignore stringer generated files? If not, the stringer module should be updated.

Example:
`
foo_stringer.go:9:5: don't use underscores in Go names; var _foo_index should be _fooIndex
`

**Comment by dsymonds** [comment]
Just don't run golint on generated code. Generated code usually has a hard time meeting the standards we expect of human-written code.

**Comment by purpleidea** [comment]
@dsymonds I understand it's not necessary for generated code to pass golint, this is why I recommended having it automatically avoid generated files. This will decrease the noise for the user.

**Comment by zimmski** [comment]
The problem is that generated code can have different suffixes or even no suffix at all. There is no general rule how generated files should be named. IMHO it is best to just whiteflag files that should not be reported as problems. I usually simply use grep to filter the output of golint https://github.com/zimmski/tavor/blob/master/.travis.yml#L28

**Comment by dmitris** [comment]
Sorry picking up an old closed issue.  Just an idea - would it be possible for golint to look for the string `// Code generated by "stringer -type=` on the first line of each .go file and if found, skip linting the file?  It wold make using golint easier (`golint ./...`) without having to do extra movements to skip certain files like
`find . -name '*.go' | xargs grep -L '// Code generated by "stringer -type='| xargs golint`

**Comment by dan-compton** [comment]
You can also just use the -output flag to create valid names for the generated file(s)
