### ISSUE TITLE
Packages that define their own Errorf cause problems with different signatures

### ISSUE THREAD

**Issue by bobbytables** [golang/lint#189]
The `grpc` package (google.golang.org/grpc) exports a function `Errorf` with a signature like so:

```go
func Errorf(c codes.Code, format string, a ...interface{}) error
```
See: https://godoc.org/google.golang.org/grpc#Errorf

This causes problems with GoLint as it attempts to call out errors with Errorf and sees that the first argument is not a string returning lint errors such as:

"Constant 5 is not a string in call to Errorf`

**Comment by dsymonds** [comment]
That's a known problem with govet, but govet is not golint.
