### ISSUE TITLE
golint does not check the function name in interface

### ISSUE THREAD

**Issue by cloudfly** [golang/lint#204]
```go
package main

// TestInterface test
type TestInterface interface {
	hello_world()
}

func hello_world() {
	println("hello world")
}

func main() {
	hello_world()
}
```

```sh
$ golint test.go
test.go:8:6: don't use underscores in Go names; func hello_world should be helloWorld
```

it does not check the uncorrect function name hello_world in TestInterface, any special reason for this?

Thanks.

**Comment by dsymonds** [comment]
It's because interface names are often constrained by concrete implementations elsewhere (because the interface exists to match some specific types), so it's not often feasible to rename the interface method. That doesn't apply to standalone funcs.
