### ISSUE TITLE
install path returns 404

### ISSUE THREAD

**Issue by mnsr** [golang/lint#206]
In my cmd prompt, i enter:
`$ go get -u github.com/golang/lint/golint`

it returns the following error:
```
# cd B:\Development\go\src\golang.org\x\tools; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package golang.org/x/tools/go/gcimporter15: exit status 128
```

https://github.com/golang/lint/golint returns a 404

**Comment by dsymonds** [comment]
Is your copy of golang.org/x/tools out of date? Consider deleting `$GOPATH/src/golang.org/x/tools` and re-running the `go get` command.

**Comment by mnsr** [comment]
Thanks for your quick reply!

That worked, thanks! Not sure how it was out of date because i only started to learn go the yesterday.
