### ISSUE TITLE
.golintrc for enabling and disabling rules

### ISSUE THREAD

**Issue by yoiang** [golang/lint#209]
Hey y'all, **golint** is great!
I understand the tool is meant to be opinionated but no rule is hard and fast. It would be great to be able to customize which rules **golint** has enabled and disabled, preferably within a repo specific file.

**Comment by dsymonds** [comment]
No, see the README.

**Comment by yoiang** [comment]
@dsymonds right, I've read through the README already, and again, and am still unclear what part of it pertains, maybe if you could explain like I was a child.

**Comment by dsymonds** [comment]
There is no need to enable or disable different rules. If you disagree with a particular style rule, just don't follow it. Or use grep if you can't bear the output.

**Comment by yoiang** [comment]
I'm sure this has already been argued in another thread so I'm just going to confirm it rather than debate it here: the offical golang stance is _follow our rules or don't use our language and tools._

Aside: using grep isn't always an option, for example when building tools on top of tools as one does when building an ecosystem.

**Comment by dominikh** [comment]
> Aside: using grep isn't always an option, for example when building tools on top of tools as one does when building an ecosystem

Tools on top of tools can still filter output.

**Comment by tsheaff** [comment]
@dominikh I know this is an old issue, but I think the response is lacking. I like that go is opinionated, but no configuration at all on a linter, especially when it includes fairly subjective rules like "must have comments for every exported function". I'm using [`vscode-go`](https://github.com/Microsoft/vscode-go) so the tools-on-tools comment is particularly relevant — I have to choose another linter fullstop, be fine with green lines everywhere, or add comments to *every single capitalized method* which I don't want to do across the whole codebase.

**Comment by dominikh** [comment]
@tsheaff you don't need to convince me, I wield no control over decisions in golint, I'm just describing the status quo. I am fairly certain that "I have to choose another linter fullstop" is the intended solution to the problem.
