### ISSUE TITLE
Avoid generated files

### ISSUE THREAD

**Issue by dsnet** [golang/lint#239]
Generated source files are not generally expected to follow proper Go style. For example, running lint on a protobuf-generated Go file reports hundreds of lint issues.

With the upcoming generator disclaimer headers, we should consider having lint ignore these types of source files: golang/go#13560

**Comment by aahoughton** [comment]
Is it jumping the gun to say that the consensus is look for one of "DO NOT EDIT" or "Code generated by" in the first comment block?

**Comment by spenczar** [comment]
Now that the code generation header is formalized via https://golang.org/s/generatedcode, this seems tractable.

**Comment by therealplato** [comment]
I'm still experiencing linting alerts for generated files. I'm running go 1.8, my `$GOPATH.../lint` repo's `master` references `c5fb716` which appears current.

I have two files generated by `protoc-gen-go` whose header block matches the pattern`// Code generated ...\n\n... DO NOT EDIT."`
I expected that when I run `golint` in the folder with these, that i would not receive warnings, but actually I still get the warnings.

Ditto for running golint from vim-go.

Unless I'm missing something, the `isGenerated` function is broken. repro'd here: https://gist.github.com/therealplato/27e1c3ea716b25674ca158c9b9496cd2

**Comment by dsnet** [comment]
You must have an old version of protoc-gen-go. This was fixed in https://github.com/golang/protobuf/commit/47eb67eaf5cab63c58956d4d4ce86b03ad5eaa03

**Comment by therealplato** [comment]
Thanks @dsnet. The code was certainly generated before that commit

**Comment by youleiy** [comment]
"go.lintFlags": [
        "--exclude=\"\bexported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported\b\""
    ]
