### ISSUE TITLE
Flag useless strings.Replace where n == 0

### ISSUE THREAD

**Issue by dsnet** [golang/lint#260]
In the `strings` package: `func Replace(s, old, new string, n int) string`

Since replacing `n == 0` elements is pretty pointless, some programmers erroneously assume that this means replace all substrings. Instead, they should have used `n == -1`.

**Comment by dominikh** [comment]
You're entering `staticcheck` territory here ([SA1010](https://github.com/dominikh/go-staticcheck#checks)) and it's a check I'm going to add myself, in symmetry with the aforementioned check.

**Comment by dsnet** [comment]
I agree. This is not a style related issue.
