### ISSUE TITLE
No golint binary is created

### ISSUE THREAD

**Issue by williamh** [golang/lint#269]
I am running golang-1.7.4 Linux/amd64.
According to your readme, I should be able to do this:

```
mkdir /home/whubbs/go
cd /home/whubbs/go
GOPATH=/home/whubbs/go go get -u github.com/golang/lint
```

then have a binary called golint.

This process completes with no error, but the binary is not created.

Thanks,

William

**Comment by dominikh** [comment]
Quoting the top of the README:

> go get -u github.com/golang/lint/golint

**Comment by williamh** [comment]
Ok, sorry about the noise, that works.
