### ISSUE TITLE
time.Parse() without time zone

### ISSUE THREAD

**Issue by pierrre** [golang/lint#280]
I think using `time.Parse()` without a time zone indicator is a bad practice.

In the documentation:
`In the absence of a time zone indicator, Parse returns a time in UTC.`
But that's probably not what the user want.

We should suggest to use `time.ParseInLocation()`.

FYI, in PHP the equivalent function parse with the "local" time zone.
I had to fix a related issue, in the code translated from PHP by another developer.

**Comment by andybons** [comment]
Thanks for the issue.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
