### ISSUE TITLE
Suggest using errors.New() instead of fmt.Errorf() when possible

### ISSUE THREAD

**Issue by dlespiau** [golang/lint#284]
When the format string doesn't have any verb, one "should" use `errors.New()` over `fmt.Errorf()`. I can see two reasons:
  - There's no need to scan the format string for verbs in that case.
  - Use the `errors` package directly allows to remove some unnecessary dependencies on the `fmt` package, which is rather large.

I'm not sure whether this belongs to vet, lint (or neither!).

**Comment by andybons** [comment]
Thanks for the note.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
