### ISSUE TITLE
"should omit type * from declaration; it will be inferred", not it won't

### ISSUE THREAD

**Issue by ghost** [golang/lint#292]
`var op Expr = Unary{'-', Literal{4}}`
Code works as expected, but:
`should omit type Expr from declaration of var op; it will be inferred from the right-hand side`

Hmm. ok... let's try it w/o:
Code doesn't work. `cannot use Binary literal (type Binary) as type Unary in assignment`
` var op = Unary{'-', Literal{4}}`

I should note that Expr is an interface.

**Comment by andybons** [comment]
> The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.

The scope of this tool is to enforce code conventions outlined in Effective Go and CodeReviewComments. In most cases this check is correct and the type will be inferred. It is meant to steer people away from writing something like `var m map[string]int = map[string]int{ ... }`
