### ISSUE TITLE
Suggest using http.Status* constants for routines expecting HTTP codes (Error, Redirect, StatusText, etc)

### ISSUE THREAD

**Issue by dgryski** [golang/lint#293]
I believe this will help readability rather than making people look up obscure HTTP status codes.

Perhaps this could be limited to only codes not in a small "well known" list.  Maybe 200, 404, 500..

**Comment by andybons** [comment]
Thanks for the issue.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
