### ISSUE TITLE
Suggest io.SeekXXX instead of os.SEEK_XXX

### ISSUE THREAD

**Issue by dsnet** [golang/lint#294]
We added the `io.SeekXxx` constants in Go1.7, we should suggest those constants when people try to use the `os.SEEK_XXX` constants.

**Comment by pravj** [comment]
@dsnet,

I would like to work on this.
If I'm allowed to do so, can you please hint me to start with this?

**Comment by shurcooL** [comment]
FWIW, there's overlap with `staticcheck`, this check already exists there as:

SA1019 – Using a deprecated function, variable, constant or field

/cc @dominikh FYI.

**Comment by andybons** [comment]
Closing due to https://github.com/golang/lint/pull/302#issuecomment-367480819
