### ISSUE TITLE
Allow custom initialisms 

### ISSUE THREAD

**Issue by thebigjc** [golang/lint#304]
I find my code reviewers are constantly pointing out inconsistent initialisms in our code. Rather than waste our time on these, I'd like lint to find them, but the current list of initialisms is hardcoded. I'd like to allow lint to read custom initialisms from a file, ideally by convention so no special flags are needed.

Happy to write this up, but wanted to see if there would be support for it.

I'm thinking adding `.lint_initialisms` or similarly named file, one initialism per line, and checking for its existence and adding to the commonInitialisms map.

What do y'all think?

**Comment by vetinari** [comment]
Check also for false positives, i.e. `DNs` ((LDAP )Distinguished Name, plural) is not something to flag when `DNS` (builtin) and `DNs` (local) are both in the list.

**Comment by andybons** [comment]
Thanks for the report.

From the README.md:

> Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free".

As this seems to be adding a knob, closing. Sorry.
