### ISSUE TITLE
ID is not necessarily an abbreviation / Freudian code

### ISSUE THREAD

**Issue by greendrake** [golang/lint#323]
The linter currently requires variables like `GatewayId` to be named `GatewayID` because of [this](https://github.com/golang/lint/blob/master/lint.go#L754).

The thing is, "Id" in cases like the above is not an initialism/abbreviation/acronym. It is just a _shortening_ from "identifier" or "identification" — not "identity document" or any other two-word term.

I therefore suggest removing `ID` from that map, because requiring to rename `GatewayId` to `GatewayID` does not make any sense.

**Comment by dominikh** [comment]
Duplicate of #89.

**Comment by andybons** [comment]
Closing due to it being a duplicate.

**Comment by berlincount** [comment]
I disagree with this issue being truly closed.
