### ISSUE TITLE
Permission denied while installing

### ISSUE THREAD

**Issue by lap00zza** [golang/lint#342]
I am trying to install lint as part of vscode-go extension. While installing I get a permission denied at the end. How can I fix it? I am attaching some screenshots below:

![1](https://user-images.githubusercontent.com/8621583/31005401-28631164-a516-11e7-8dee-645ecf2879de.png)
![2](https://user-images.githubusercontent.com/8621583/31005411-301a4fb2-a516-11e7-8cb5-0df3c1fbf30d.png)

## Addtional info
* Go version `go version go1.8.3 windows/amd64`

**Comment by andybons** [comment]
It looks like your permissions are not properly set up. Also, questions are better suited for a mailing list. https://github.com/golang/go/wiki/Questions
