### ISSUE TITLE
GoLint Tool not giving errors

### ISSUE THREAD

**Issue by apandit24** [golang/lint#361]
I was running golint tool on go program but it is not able to detect errors such as blank if

**My program**
: package main
import "fmt"
func main() {
fmt.Println("Hello,World!")
var b int
for b := 0; b < 10; b++ {
if(b<10) {

	}	
}
}

I am running golint  from command line
**Command**: golint filename.go

Please help me out i am unable to understand since it is not giving any o/p

**Comment by andybons** [comment]
Thanks for the note.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
