### ISSUE TITLE
Unable to install GoLint at correct path

### ISSUE THREAD

**Issue by aksh7860** [golang/lint#362]
I am unable to install GoLint at its Correct Path .After running the command to install GoLint it is not showing under my go installed path in CentOS (/usr/local/go/bin)

Please help me out i am unable to understand this

**Comment by andybons** [comment]
Could you paste the output of what commands you tried when you attempted to install?

If you installed via `go get`, then the `-v` flag should show you what is happening under the hood.

**Comment by aksh7860** [comment]
Their was some issues while downloading ... got it rectified .... I am closing this issue.Thanks for the reply
