### ISSUE TITLE
remote origin not found

### ISSUE THREAD

**Issue by blavkboy** [golang/lint#367]
Tried running "go get github.com/golang/lint/golint" and I got "package github.com/golang/lint: remote origin not found"

**Comment by andybons** [comment]
Can you paste the output of `go get -u -v github.com/golang/lint/golint`?

**Comment by blavkboy** [comment]
![golint](https://user-images.githubusercontent.com/25582653/34427434-ce70d28c-ec4a-11e7-8990-fe812fc0cdb7.png)
Not sure if you'll see this picture.

**Comment by andybons** [comment]
+ Are you able to `go get` other packages?
+ Is there a .git folder in `C:\Go\src\github.com\golang\lint`? Are there .git folders in other package directories?

You may need to remove the folder and try to `go get` again.

**Comment by blavkboy** [comment]
You're right, I found that directory with the .git folders in it. Looks like it's working. Thank you so much, I didn't realize I messed up the first download since it was through VSC. Thank you.
