### ISSUE TITLE
Why we can't have this in golint? vetshadow warning?

### ISSUE THREAD

**Issue by johnunclesam** [golang/lint#370]
Why we can't have this in golint?

https://github.com/Microsoft/vscode-go/issues/1455#issuecomment-360305829

**Comment by andybons** [comment]
Thanks for the Issue.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
