### ISSUE TITLE
Why is Hungarian notation checking only the name whose head is "k"?

### ISSUE THREAD

**Issue by morix1500** [golang/lint#371]
Hello.
I saw the following issue and understood that Hungarian notation is not recommended.
https://github.com/golang/lint/issues/258

But why are you checking only "k"?
https://github.com/golang/lint/blob/master/lint.go#L561

I am not troubled by this, but I am interested in it.

**Comment by mattn** [comment]
FYI: Recently I have not seen, for long ago Objective-C users often uses the name with prefix k to mean that the variable is const. `const` -> `konst` -> `k`

**Comment by morix1500** [comment]
I get it. Thank you!
