### ISSUE TITLE
Proposal: Comments of exported name should have a valid end of sentence.

### ISSUE THREAD

**Issue by vkuzmin-uber** [golang/lint#374]
This is a well known rule https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences. 

golang/golint already requires "comment on exported function/type TTT should be of the form "TTT ... ". And I think it should also enforce end period.

So, full check and error should be:

"comment on exported function/type XXX should be of the form "TTT ... .", not end period"

What do you think? If I get approval on it, I am willing to implement it.

**Comment by vkuzmin-uber** [comment]
After investigation, I have found that period is not only "valid" end of sentence. So, we should follow common sense and practice. Check for list of symbols that can be a valid end:

// List of symbols that can end a sentence.
// Note that it doesn't follow grammar rules but common sense instead.
const symbolsCanEndASentence = ".?!;\"'`\\/|)}]>/#$"

**Comment by andybons** [comment]
Can you point to instances where # or $ is considered a valid end of a sentence? Where is the list of symbols from?

**Comment by vkuzmin-uber** [comment]
Andy, appreciate you feedback.

I’ve created the list after some speculations like: “wold I want to omit “period” intentionally if it were …”

1) 
// GeneratePatern returns regex using given keyword: ^.*keyword$
func GeneratePatern(keyword string) bool

2) For #, I mostly thought about comment that 
// CountNumberOfLines returns number of lines in script. 
// Note that it ignores lines that starts with symbol #
func CountNumberOfLines(f ScriptFile) int 

I understand that in both cases author may avoid this, at least with quotes (and this is why I put ' and " in the list):

1) … using given keyword: ‘^.*hello$’
2) … that starts with symbol “#”

But as a "linter" I’d accept $ and # as a valid end of sentence instead. Then "reviewers" may ask to change it if necessary. 

I also received request to add : to the list but personally I think that symbol : at the end is confusing, it means either typo or author forgot to complete sentence.

**Comment by vkuzmin-uber** [comment]
Added a check for type's directive in comment that easyjson requires:

//easyjson:json

I decided that it's just better to igbnore comment that has this directive,

**Comment by vkuzmin-uber** [comment]
@andybons  if you still have a concern about "# or $", please let me know. I still think that we need some rule to support https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences . Current implementation os pretty soft but it already covers most of needs. I am willing to respond on future issue if any and provide fixes. 

Let me know please if this is sound feature.

**Comment by andybons** [comment]
I don't believe these are valid ends to a sentence. Given your example:

> Note that it ignores lines that starts with symbol #

It could be written as `Note that it ignores lines that starts with symbol #.` (the singular form of symbol would indicate that it refers only to the # and not the period) or `Note that it ignores lines that start with the # symbol.` to disambiguate between the # and period.

**Comment by vkuzmin-uber** [comment]
Well, this is selection between: 

1. "Report when we think that end of sentence is required and don't report when we are not sure"

2. "Don't report at all, but claim that every sentence must end with period https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences"

Personally I prefer 1.

**Comment by vkuzmin-uber** [comment]
As follow up, I have updated comment at https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

**Comment by andybons** [comment]
Please feel free to send a note to golang-nuts@googlegroups.com to ask about this.

**Comment by shurcooL** [comment]
> After investigation, I have found that period is not only "valid" end of sentence.

Can you share that investigation?

I agree with @andybons's [comment](https://github.com/golang/lint/issues/374#issuecomment-367450340) above, that sentence ending with `#` should be written to end with a period. The characters `!` and `?` might be valid characters to end a sentence with, but I'm not sure they're neccessary to support in godoc. I can't think of any high quality Go symbol documentation that can't end with a period.

> As follow up, I have updated comment at https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

That wiki page says at the top:

> Please discuss changes before editing this page, even minor ones.

Did you discuss that change somewhere (other than here)?

> and so on. Note that there are other symbols except a period that can be a valid end of sentence (at least !, ?). Apart from there are many tools that use comments to mark types and methods (like easyjson:json and golint's MATCH). It makes this rule a hard to formalize.

This is in conflict with what it says above, that "Comments should begin with the name of the thing being described and end in a period." The sentence mentioning easyjson and MATCH is confusing; I don't understand what those mean exactly. "It makes this rule a hard to formalize." is also something that I'm not sure about.

**Comment by vkuzmin-uber** [comment]
Well, I agree that there are a lot of Cons agains this fix. I am fine to have my own fork and hope to get it in the other tool eventually where features are configurable https://github.com/dominikh/go-tools/issues/264

My point about the fix I suggested - this is much better than nothing. It catches 99% of "regular" cases, when period is required and it does *nothing* (as it does now) if meet !? and etc.

Good example: this fixes catches "absent period" in the golint code (tests)

About #

Example:

// ... that starts with sequence ;#

// ... that starts with ;#.

I, as reviewer, would accept "no period" here, because I know that some people don't want that somebody treat "." as a part of sequence. Yes, you may workaround it but namely in cases like that I am ok if linter ignores it.

Anyway, thanks for discussion. This shows that this feature can't be a part of tools without configuration/flexible rules. I hope that with possibility to enable/disable/configure, it can be implemented at "staticcheck".
