### ISSUE TITLE
Tag and release a stable version (1.0?)

### ISSUE THREAD

**Issue by mcandre** [golang/lint#378]
Thank you for publishing the wonderfully helpful golint system for identifying sensitive Go code! Could we get a git tag and release version, say v1.0, for this project? That way, developers can have confidence that they are using a specific version of golint, in case of any future changes that might break backwards compatibility.

**Comment by andybons** [comment]
Why do you need backwards compatibility? We state in the readme:

> In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.

**Comment by andybons** [comment]
Closing due to no response.
