### ISSUE TITLE
Linter doesn't care about comment style

### ISSUE THREAD

**Issue by gyurobenjamin** [golang/lint#379]
Linter allow you to do any of these:
```go
//PublicStruct ...

type PublicStruct struct {}
```

```go
// PublicStruct ...

type PublicStruct struct {}
```

**Comment by andybons** [comment]
Thanks for the issue.

This appears to be [out of scope](https://github.com/golang/lint/blob/master/README.md#scope) and so is being closed. If you feel this is in error please feel free to re-open.

Please note this is not the forum to discuss edits to [CodeReviewComments](https://golang.org/wiki/CodeReviewComments). If you wish to propose changes to it please send a mail to [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts).
