### ISSUE TITLE
readme gives wrong vim instructions

### ISSUE THREAD

**Issue by mperham** [golang/lint#403]
README says to install via `go get -u golang.org/x/lint/golint` but the VIM plugin says to add this: `set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim`.  That path would only exist if we ran `go get -u github.com/golang/lint`  Those are conflicting locations, need to use one or the other.

https://github.com/golang/lint#vim

**Comment by michal-franc** [comment]
You can close this it was fixed by #405
