### ISSUE TITLE
bazel build with no such package @org_golang_x_sys//unix

### ISSUE THREAD

**Issue by ranchochen** [golang/lint#404]
Hi, 
   i was using **bazel build XXX**, and i encountering the problem as below:

> no such package '@org_golang_x_sys//unix': failed to fetch org_golang_x_sys: 2018/06/24 00:04:36 unrecognized import path "golang.org/x/sys

   i've tried to make efforts as:

> mkdir -p $GOPATH/src/golang.org/x/sys  
   git clone https://..../sys.git

  
   but still the same, anyone knows why?

  ps:
  bazel vesion is 0.14.1

**Comment by andybons** [comment]
This is the lint repo. Perhaps you want https://github.com/bazelbuild/rules_go ?
