### ISSUE TITLE
Detect ending carriage return or punctuation in fmt.Fatalf

### ISSUE THREAD

**Issue by ksbeking** [golang/lint#406]
The linter detects carriage returns or punctuation at the end fo fmt.Errorf, why shouldn't it do so for fmt.Fatalf?

**Comment by andybons** [comment]
`fmt.Errorf` returns an error, while `log.Fatalf` (there is no `fmt.Fatalf`) logs to stderr. It’s perfectly reasonable to log messages to contain punctuation or carriage returns at the end.
