### ISSUE TITLE
Comment in import package is causing go get command to fail.

### ISSUE THREAD

**Issue by larrymjordan** [golang/lint#416]
Hi, the changes you made in https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58, made my CI to crash when doing
`go get github.com/golang/lint/golint`  the error messages is:

`package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"`

**Comment by andybons** [comment]
Duplicate of #415
