### ISSUE TITLE
Cannot use go get 

### ISSUE THREAD

**Issue by vincentMrg** [golang/lint#417]
Hello

When I try to go get the project I got

$ go get -u github.com/golang/lint/golint
package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"

It's probably due to commit 5906bd5c48cd840279ace88b165057fbbd7fb35a

**Comment by Strawberryww** [comment]
@vincentMrg yes, I also found the same issue. @zchee, could you help resolve it? Thanks.

**Comment by dominikh** [comment]
Use the correct path: https://github.com/golang/lint#installation

**Comment by zchee** [comment]
@vincentMrg @Strawberryww Hi,

I explain this.
The `lint` repository has been hosted on the `golang.org/x/lint` after the https://github.com/golang/lint/commit/ead987a65e5c7e053cf9633f9eac1f734f6b4fe3
It's a Go core maintainers plan. I don't know why switch to `golang.org`.

Anyway, this repository's actual import path is `golang.org/x/lint`, I was changed canonical import path with just respect this.
https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58

---

/cc @ccojocar @bonifaido
You should change `lint` package import path to `golang.org/x/lint`.

---

@bradfitz Sorry for mention, Could you helped me?

**Comment by zchee** [comment]
@dominikh Thanks, your correct.

**Comment by vincentMrg** [comment]
Nice, Thank you all

**Comment by Strawberryww** [comment]
@zchee, @dominikh , It worked, thank you!

**Comment by andybons** [comment]
Duplicate of #415
