### ISSUE TITLE
Necessity of import comments

### ISSUE THREAD

**Issue by packrat386** [golang/lint#418]
Perhaps this isn't the right venue to have this discussion, in which case I can close this, but I was wondering if there's a particular reason to enforce importing from a certain source (https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58). There seems to be a lot of code in "the wild" importing this project from github.com as evinced by a number of closed issues asking why their usual `go get` isn't working. There's also the issue that this repo is more discoverable by people looking for tooling than the repo(s) at `golang.org/x`. Given the ease-of-use aspect, is there a compelling reason to prevent people from pulling this from the github mirror? 

I suppose we've already collectively bitten the bullet on this particular repo, but is this going to be the standard going forward for everything in `golang.org/x`?

**Comment by andybons** [comment]
Thanks for the issue. This discussion is better had on golang-nuts.
