### ISSUE TITLE
Error getting package

### ISSUE THREAD

**Issue by LourdesMoran** [golang/lint#419]
I have a project that uses golint and installs it inside the docker container. It have been working ok for month (and have been built multiple times), but today when I build the container again I get the following error:
go get -u github.com/golang/lint/golint

`package github.com/golang/lint/golint: code in directory  /a-go-path/golang/lint/golint expects import "golang.org/x/lint/golint"`

I can replicate the issue locally on my computer by typing `go get github.com/golang/lint/golint`. I am using go 1.11.0

**Comment by kelbyers** [comment]
This is happening to me for both go version 1.10 and 1.11:

```
$ goenv shell 1.10.4

$ go version
go version go1.10.4 darwin/amd64

$ go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory /Users/jxb2016/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"

$ ls $GOPATH/bin/golint
ls: /Users/jxb2016/go/bin/golint: No such file or directory
```

```
$ goenv shell --unset

$ go version
go version go1.11.1 darwin/amd64

$ go get -u -v github.com/golang/lint/golint
github.com/golang/lint (download)
package github.com/golang/lint/golint: code in directory /Users/jxb2016/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"

$ ls $GOPATH/bin/golint
ls: /Users/jxb2016/go/bin/golint: No such file or directory
```

**Comment by kelbyers** [comment]
I am able to install the actual package that `github.com/golang/lint/golint` imports:

```
$ go get -u golang.org/x/lint/golint

$ ls $GOPATH/bin/golint
/Users/jxb2016/go/bin/golint
```

**Comment by LourdesMoran** [comment]
The package is just installed by go get -u golang.org/x/lint/golint.

**Comment by andybons** [comment]
Duplicate of #415
