### ISSUE TITLE
unrecognized import path during go get

### ISSUE THREAD

**Issue by agnivade** [golang/lint#440]
This just started to break our CI buils. It is in normal GOPATH mode.

```
go get -u -v golang.org/x/lint/golint
Fetching https://golang.org/x/lint/golint?go-get=1
Parsing meta tags from https://golang.org/x/lint/golint?go-get=1 (status code 502)
package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (parse https://golang.org/x/lint/golint?go-get=1: no go-import meta tags ())
```
I note that this does not happen locally on my laptop. Only on my CI server.

Related https://github.com/golang/lint/issues/397.

@dmitshur / @andybons - any issues ?

**Comment by dmitshur** [comment]
I've opened https://github.com/golang/go/issues/30619, I think it's related to this.

**Comment by dmitshur** [comment]
Are you still seeing this now? After https://github.com/golang/go/issues/30619#issuecomment-469973076?

**Comment by agnivade** [comment]
Looks good now. Thanks @dmitshur
