### ISSUE TITLE
how to configure vim?

### ISSUE THREAD

**Issue by tfarina** [golang/lint#81]
Hi,

I have this in my ~/.vimrc:

 filetype plugin indent on
 set rtp+=~/golib/src/github.com/golang/lint/misc/vim

But when I run ':Lint' in a go file vim says:
E492: Not an editor command: Lint

What am I missing?

Thanks!

**Comment by oryband** [comment]
@tfarina I recommend to use syntastic, a syntax checker plugin common among vim users. I has built in `golint` support. Should make your life easier.

https://github.com/scrooloose/syntastic

**Comment by oryband** [comment]
@dsymonds perhaps you should reference syntastic in the docs.

**Comment by youngchopin** [comment]
i have move this cmd to the first line of ~/.vimrc and /etc/vimrc, i still got the error "E492: Not an editor command: Lint"

`set rtp+=/home/myname/go/src/github.com/golang/lint/misc/vim`

@dsymonds

**Comment by fanux** [comment]
check your golint is work. If not add it in $PATH
```
export PATH=$PATH:$GOPATH/bin
```
