### ISSUE TITLE
cannot make "lint.go"

### ISSUE THREAD

**Issue by Alexey-T** [golang/lint#93]
Go1.4/Win64. 

    C:\Go\src\github.com\golang\lint>go build lint.go
    # command-line-arguments
    .\lint.go:1401: assignment count mismatch: 2 = 3
    C:\Go\src\github.com\golang\lint>

cannot make.

**Comment by dsymonds** [comment]
You probably need to update your x/tools repo:
```
  go get -u golang.org/x/tools
```

**Comment by Alexey-T** [comment]
updated (both x/tools and golang/lint). now:

    C:\Go\src\github.com\golang\lint\golint>go build golint.go
    # command-line-arguments
    .\golint.go:44: undefined: allPackagesInFS
    .\golint.go:52: undefined: importPaths

**Comment by dsymonds** [comment]
Don't use a list of filenames with `go build`. You've skipped the `import.go` file. Just run `go build`.

**Comment by Alexey-T** [comment]
Tks David :]
