### ISSUE TITLE
how to see all errs in output list?

### ISSUE THREAD

**Issue by Alexey-T** [golang/lint#94]
i made err file

    func f(2__) {{{{ // ok
    }

now golint shows this:

    er.go:7:8: expected type, found 'INT' 2 (and 6 more errors)

how to see all 7 errs?
(not 1 error)

**Comment by dsymonds** [comment]
That's an error coming from the Go parser. `Golint`assumes you have a well-formed Go source file. You could try running `gofmt` on the source file to get the full list of parse errors.

**Comment by Alexey-T** [comment]
and u cannot "fix" it?

**Comment by dsymonds** [comment]
No, `golint` is in the business of pointing out style issues with your code, not dealing with completely broken code that won't even compile.
