### ISSUE TITLE
Golint build error - go version 1.4

### ISSUE THREAD

**Issue by ixos** [golang/lint#97]
[root@dev /usr/src/go/src/github.com/golang/lint] go version
go version go1.4 linux/amd64

[root@dev /usr/src/go/src/github.com/golang/lint] go build
./lint.go:1423: assignment count mismatch: 2 = 3
[root@dev /usr/src/go/src/github.com/golang/lint] git diff
diff --git a/lint.go b/lint.go
index dc58a45..713bcbc 100644
--- a/lint.go
+++ b/lint.go
@@ -1420,11 +1420,11 @@ func (f *file) isUntypedConst(expr ast.Expr, scope *types.Scope) (defType string
 
        // Re-evaluate expr outside of its context to see if it's untyped.
        // (An expr evaluated within, for example, an assignment context will get the type of the LHS.)
-       tv, err := types.EvalNode(f.fset, expr, f.pkg.typesPkg, scope)
+       tv, _, err := types.EvalNode(f.fset, expr, f.pkg.typesPkg, scope)
        if err != nil {
                return "", false
        }
-       if b, ok := tv.Type.(*types.Basic); ok {
+       if b, ok := tv.Underlying().(*types.Basic); ok {
                if dt, ok := basicTypeKinds[b.Kind()]; ok {
                        return dt, true
                }

**Comment by dsymonds** [comment]
You probably have an old version of a dependent package. Try running `go get -u golang.org/x/tools`.

**Comment by ixos** [comment]
yes, sorry, stuipid mistake :/
